name: Publish Python Package to JFrog Artifactory
on:
 push:
   branches:
     - master  # Or specify the branch you want to trigger the workflow
jobs:
 publish:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.12'  # Specify your Python version

     - name: Create .pypirc file
       run: |
          tee ~/.pypirc > /dev/null <<EOF
          [distutils]
          index-servers =
            local

          [local]
          repository = https://${{ secrets.ARTIFACTORY_URL }}/artifactory/api/pypi/poc-pypi
          username = ${{ secrets.ARTIFACTORY_USERNAME }}
          password = ${{ secrets.ARTIFACTORY_PASSWORD }}
          EOF

     - name: Install build tools
       run: |
         python3 -m pip install --upgrade pip
         pip3 install virtualenv
         python3 -m venv venv
         source venv/bin/activate
         pip3 install setuptools wheel twine
         python3 setup.py sdist bdist_wheel
         twine upload --repository local dist/*
