name: Publish Python Package to JFrog Artifactory
on:
 push:
   branches:
     - main  # Or specify the branch you want to trigger the workflow
jobs:
 publish:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.4'  # Specify your Python version
     - name: Install build tools
       run: |
         python -m pip install --upgrade pip
         pip install setuptools wheel twine
     - name: Build the package
       run: |
         python setup.py sdist bdist_wheel
     - name: Publish to JFrog Artifactory
       env:
         TWINE_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
         TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_API_KEY }}
       run: |
         pip install twine
         twine upload --repository-url "${{ secrets.ARTIFACTORY_URL }}/pypi-local/" dist/*
