name: Publish Python Package to JFrog Artifactory
on:
 push:
   branches:
     - main  # Or specify the branch you want to trigger the workflow
jobs:
 publish:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.12'  # Specify your Python version

     - name: Create .pypirc file
       run: |
          cat > ~/.pypirc <<EOF
          [distutils]
          index-servers =
            artifactory
 
          [artifactory]
          repository = https://${{ secrets.ARTIFACTORY_URL }}/artifactory/api/pypi/<REPOSITORY>
          username = ${{ secrets.ARTIFACTORY_USERNAME }}
          password = ${{ secrets.ARTIFACTORY_PASSWORD }}
          EOF

     - name: Install build tools
       run: |
         pip3 install virtualenv
         python3 -m venv venv
         source venv/bin/activate
         python3 -m pip install --upgrade pip
         pip install setuptools wheel twine
         
     - name: Build the package
       run: |
         python3 setup.py sdist bdist_wheel
         
     - name: Publish to JFrog Artifactory
       run: |
         twine upload --repository local dist/*
